#!/bin/bash

# 🤖 Auto-Commit Generator Script
# This script creates 6-7 commits with different timestamps
# and automatically pushes them to the repository

set -e

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${BLUE}╔════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║  🤖 Auto-Commit Generator Started   ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════╝${NC}"

# Number of commits to create (default: 7)
COMMIT_COUNT=${1:-7}

# Create ACTIVITY_LOG.md if it doesn't exist
if [ ! -f "ACTIVITY_LOG.md" ]; then
  cat > ACTIVITY_LOG.md << 'EOF'
# 📊 Activity Log

This file tracks automated commits generated by the Auto-Commit workflow.

## Commit History

EOF
fi

echo -e "${YELLOW}📝 Creating $COMMIT_COUNT commits with different timestamps...${NC}"
echo ""

# Get current timestamp
CURRENT_TIME=$(date +%s)
DAYS_BACK=2  # Spread commits over 2 days
SECONDS_PER_COMMIT=$((86400 * $DAYS_BACK / $COMMIT_COUNT))  # Seconds per commit

for i in $(seq 1 $COMMIT_COUNT); do
  # Calculate timestamp for this commit (going backwards)
  COMMIT_TIME=$((CURRENT_TIME - SECONDS_PER_COMMIT * ($COMMIT_COUNT - i)))
  COMMIT_DATE=$(date -d "@$COMMIT_TIME" '+%Y-%m-%d %H:%M:%S')
  COMMIT_ISO=$(date -d "@$COMMIT_TIME" '+%Y-%m-%dT%H:%M:%S')
  
  # Update ACTIVITY_LOG.md
  cat >> ACTIVITY_LOG.md << EOF

### Commit #$i
- **Timestamp**: $COMMIT_DATE
- **ISO Format**: $COMMIT_ISO
- **Status**: ✅ Auto-generated
- **Activity**: Routine maintenance and updates
EOF

  # Stage the changes
  git add ACTIVITY_LOG.md
  
  # Commit with the calculated timestamp
  git commit \
    --date="$COMMIT_DATE" \
    -m "📅 Auto-Commit #$i - $(date -d "@$COMMIT_TIME" '+%A, %B %d, %Y at %H:%M:%S UTC')" \
    --allow-empty
  
  echo -e "${GREEN}✓ Commit #$i created at $COMMIT_DATE${NC}"
done

echo ""
echo -e "${BLUE}╔════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║  📊 Summary                            ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════╝${NC}"

echo -e "${GREEN}✓ Successfully created $COMMIT_COUNT commits${NC}"
echo -e "${GREEN}✓ All commits have unique timestamps${NC}"
echo -e "${GREEN}✓ Activity log updated${NC}"
echo ""
echo -e "${YELLOW}Recent commits:${NC}"
git log --oneline -n $COMMIT_COUNT

echo ""
echo -e "${GREEN}🎉 Auto-Commit Generation Complete!${NC}"
echo -e "${BLUE}The commits will be automatically pushed by the GitHub Action.${NC}"
