# 🤖 Auto-Commit Generator Script (PowerShell Version)
# This script creates 6-7 commits with different timestamps
# Usage: .\auto-commit.ps1 [CommitCount]

param(
    [int]$CommitCount = 7,
    [switch]$TestMode = $false
)

# Colors
$Green = "Green"
$Blue = "Cyan"
$Yellow = "Yellow"

Write-Host "`n╔════════════════════════════════════════╗" -ForegroundColor $Blue
Write-Host "║  🤖 Auto-Commit Generator Started   ║" -ForegroundColor $Blue
Write-Host "╚════════════════════════════════════════╝`n" -ForegroundColor $Blue

# Check if git is available
try {
    git --version | Out-Null
} catch {
    Write-Host "❌ Git is not installed or not in PATH" -ForegroundColor Red
    exit 1
}

# Configure git if not already done
Write-Host "⚙️  Configuring Git..." -ForegroundColor $Yellow
git config user.name "🤖 Auto-Commit Bot" | Out-Null
git config user.email "auto-commit-bot@github.local" | Out-Null

# Create ACTIVITY_LOG.md if it doesn't exist
if (-not (Test-Path "ACTIVITY_LOG.md")) {
    Write-Host "📝 Creating ACTIVITY_LOG.md..." -ForegroundColor $Yellow
    @"
# 📊 Activity Log

This file tracks automated commits generated by the Auto-Commit workflow.

## Commit History

"@ | Out-File -FilePath "ACTIVITY_LOG.md" -Encoding UTF8
}

Write-Host "📝 Creating $CommitCount commits with different timestamps...`n" -ForegroundColor $Yellow

# Get current timestamp
$CurrentTime = Get-Date
$DaysBack = 2  # Spread commits over 2 days
$SecondsPerCommit = [int](86400 * $DaysBack / $CommitCount)

for ($i = 1; $i -le $CommitCount; $i++) {
    # Calculate timestamp for this commit (going backwards)
    $CommitTime = $CurrentTime.AddSeconds(-$SecondsPerCommit * ($CommitCount - $i))
    $CommitDateStr = $CommitTime.ToString("yyyy-MM-dd HH:mm:ss")
    $CommitIso = $CommitTime.ToString("yyyy-MM-ddTHH:mm:ss")
    $DayName = $CommitTime.ToString("dddd")
    $Month = $CommitTime.ToString("MMMM")
    $Day = $CommitTime.Day
    $Year = $CommitTime.Year
    $TimeStr = $CommitTime.ToString("HH:mm:ss")
    
    # Update ACTIVITY_LOG.md
    $LogEntry = @"

### Commit #$i
- **Timestamp**: $CommitDateStr
- **ISO Format**: $CommitIso
- **Status**: ✅ Auto-generated
- **Activity**: Routine maintenance and updates
"@
    
    Add-Content -Path "ACTIVITY_LOG.md" -Value $LogEntry -Encoding UTF8
    
    # Stage the changes
    git add ACTIVITY_LOG.md | Out-Null
    
    # Commit with the calculated timestamp
    $CommitMsg = "📅 Auto-Commit #$i - $DayName, $Month $Day, $Year at $TimeStr UTC"
    
    if ($TestMode) {
        Write-Host "🧪 [TEST MODE] Would create commit: $CommitMsg" -ForegroundColor Yellow
        Write-Host "   Timestamp: $CommitDateStr`n" -ForegroundColor Yellow
    } else {
        # Create commit with backdated timestamp
        git commit --date=$CommitDateStr -m $CommitMsg --allow-empty 2>&1 | Out-Null
        Write-Host "✓ Commit #$i created at $CommitDateStr" -ForegroundColor $Green
    }
}

Write-Host "`n╔════════════════════════════════════════╗" -ForegroundColor $Blue
Write-Host "║  📊 Summary                            ║" -ForegroundColor $Blue
Write-Host "╚════════════════════════════════════════╝`n" -ForegroundColor $Blue

if (-not $TestMode) {
    Write-Host "✓ Successfully created $CommitCount commits" -ForegroundColor $Green
    Write-Host "✓ All commits have unique timestamps" -ForegroundColor $Green
    Write-Host "✓ Activity log updated`n" -ForegroundColor $Green
    
    Write-Host "Recent commits:" -ForegroundColor $Yellow
    $logOutput = git log --oneline -n $CommitCount
    Write-Host $logOutput -ForegroundColor $Green
    
    Write-Host "`n🎉 Auto-Commit Generation Complete!" -ForegroundColor $Green
    Write-Host "Ready to push to GitHub!`n" -ForegroundColor $Blue
} else {
    Write-Host "✓ Test mode completed successfully" -ForegroundColor $Green
    Write-Host "Run without -TestMode flag to actually create commits`n" -ForegroundColor $Yellow
}
